name: Load secrets from 1Password

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  oidctest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
     - uses: 1Password/load-secrets-action@v5
       with:
          export-env: true
       env:
          OP_WORKLOAD_ID: "4LDL6GRCH5CDVCXW4VCUCX6FGM"
          OP_ENVIRONMENT_ID: "m7tajxoidkcbyiqzuxpacinhwm"
          OP_INTEGRATION_KEY: ${{ secrets.OP_INTEGRATION_KEY }}
