name: Dependcy Security Audit
on: [push, pull_request]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v5
        with:
          version: latest
      - run: pnpm audit --audit-level=high

  nix-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v27
      - run: nix flake check
      - run: nix-shell -p vulnix --run "vulnix --flake ."